[[ScopeOfTheIE]]

== Scope of the IE

=== Background

Since 2008, Members of the OGC/WMO Hydrology Domain Working Group have been developing the WaterML 2.0 standards for the transmission of a broad suite of water information. Interoperability of water quality data is critical to improved management of water resources and depends on the use of common semantics (vocabularies/taxonomies) and technical scenarios.

Furthermore, sharing of water quality data globally and nationally is currently limited. This is likely due to a lack of shared international standards and practices in this area and to the variety and distribution of responsibilities across agencies at national scale in the field of water quality. Some practices do already exist, most commonly on a per country basis (e.g., US WQX, French Sandre, etc.) with the exception of the EU environmental reporting in the field of water (EU WFD/WISE and EIONET-related reporting). However, in most cases those practices are not based on current internationally-agreed semantic and technical interoperability practices (OGC, W3C, RDA).

Establishment of international standards for water quality data is a key activity towards enhancing the availability of water quality information at the global level and increasing the effectiveness of development activities.

The IE will build on:
* The experience gained and data assets available from existing systems;
* The OGC Standards Baseline:
** semantics: WaterML2.0 suite of standards, Observations, Measurements and Samples (OMS),
** technical: OGC API - Features, OGC SensorThings API, OGC API - EDR;
* Early attempts applying interoperability best practices in this field (e.g., OGC WaterML-WQ Best practice, 14-003, EU API4INSPIRE project, “A Harmonized Vocabulary For Water Quality” DOI:10.13140/RG.2.1.2490.4404);
* W3C best practices: (spatial) data on the web best practices, JSON-LD, SOSA/SSN; and
* Research Data Alliance (RDA) work on observable properties (I-ADOPT).

The participants propose to vet the existing OGC Standards Baseline for common Water Quality data exchange use cases and build consensus with a broad community (WMO, RDA, others) for how to express water quality observation and sampling information.

The interoperability experiment will deliver an Engineering Report (ER) outlining opportunities to use existing technology, update the WaterML2 Best Practice for water quality, and set the stage for a WMO endorsed data exchange standard for water quality (including shared variables).

=== Objectives

The objectives of this IE include the following.
(1)	Extend and complement existing work of the HDWG, with the goal of advancing the development of WaterML 2.0 suite of standards to the sub domain of water quality observations.
(2)	Develop a shared understanding of the dimensions of interoperability required for prominent use cases involving water quality data for both surface and ground waters.
(3)	Design and test data interchange mechanisms and vocabularies that achieves the needs of stakeholder organizations and systems.
(4)	Complete an ER in the form of either a Best Practice or Standard  depending on IE outcomes.
(5)	Increase interoperability between in-situ and remote sensing data about water quality.

=== Organizational Use Cases

The following initiatives for the basis for the Organizational use cases to be considered in the IE.
* WMO Hydrologic Observing System Data Sharing Globally
* US Water Quality Data Exchange & “Internet of Water” in the US
* Water Quality Data Portal Unified Data Output Format
* International Water Quality Data Sharing in the EU
* French national legacy Water Quality system data exposed to research organizations
* Interoperability between continuous/sensor data and discrete/sample data

The above high-level Organizational use cases will provide overall framing for the IE, but ultimately, the experiment will address specific water quality domain use cases. The specific definition of these domain use cases will be determined as an initial component of the experiment. Potential Water Quality Domain Use Cases include:
* Surface water chemistry: mainly water samples and chem concentration;
* Surface water hydrobiology, microbiology: taxa occurrence, indices calculation;
* Surface water hydromorphology: category observation (shape/type of bank, flow ‘morphology’, etc.);
* Ground water chemistry: mainly water samples and chemical concentration; and
* Ground water microbiology: taxa occurrence, indices calculation.
